language: node_js
jobs:
  include:
    - node_js: "stable"
      addons:
        chrome: stable
      script: "npm run test:ci:all"
    - node_js: "10"
      script: "npm run test:ci"
    - node_js: "8"
      script: "npm run test:ci"
