language: node_js
jobs:
  include:
    - node_js: "stable"
      name: "Test-Environemnts"
      addons:
        chrome: stable
      dist: xenial
      services:
        - xvfb
      script: "npm run test:ci:env"
    - node_js: "stable"
      script: "npm run test:ci"
    - node_js: "10"
      script: "npm run test:ci"
    - node_js: "8"
      script: "npm run test:ci"
